### ISSUE TITLE
THR320D main relay configuration needs to be a momentary switch?

### ISSUE THREAD

**Issue by ryan-lang** [esphome-devices/esphome-devices#341]
@fgolemo, thanks so much for doing the legwork on this device -- your instructions got me up and running in no time.

However, I ran into an issue with the configuration provided for the main relay. I was sometimes unable to reproduce a successful toggle, (even when manually toggling the switches by hand via the web interface), other times it seemed to work fine.

The discussion [here](https://github.com/arendst/Tasmota/issues/15856#issuecomment-1172912259) seems to indicate that the relay is bi-stable, or latching. That would suggest that voltage doesn't need to be held on the relay, as in a switch, but rather requires a pulse to toggle.

Upon testing, I'm getting stable results by pulsing relay1 for ON, and pulsing relay2 for OFF. The esphome solution for a latching relay of this sort seems to be to use a [momentary switch](https://esphome.io/components/switch/gpio.html#momentary-switch) configuration, which appears to be working well for me so far.

I'd be happy to offer a pull request to tweak the configuration, but wanted to check to see if you're finding the original config to be stable, or if my suggestion might be an improvement.

Thanks!

**Comment by ryan-lang** [comment]
For reference, here are the relevant changes in my config:
```
switch:
  - platform: gpio
    id: relay1
    internal: True
    pin:
      number: GPIO19
      inverted: true
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay1
  - platform: gpio
    id: relay2
    internal: True
    pin:
      number: GPIO22
      inverted: true
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay2
```

```
climate:
  - platform: thermostat
    heat_action:
      - switch.turn_on: relay1
      - switch.turn_on: ${id}_onoff_led
    idle_action:
      - switch.turn_on: relay2
      - switch.turn_off: ${id}_onoff_led
```
