### ISSUE TITLE
Shelly Plus Plug S - Support

### ISSUE THREAD

**Issue by DejanBukovec** [esphome-devices/esphome-devices#362]
Hi,

I have Shelly Plus Plug S for which I see is not added as supported device. It is new device which have RGB LED ring...
Can someone help me integrate it into ESPHOME(For HomeAssistant) to get everything work like on older devices?

Product link:
https://www.shelly.cloud/en/products/shop/shelly-plus-plug-s

Thanks for help and any sugestions how to use it in ESPHOME ...

**Comment by felixlungu** [comment]
can you extract the pcb from the socket?
the pads can be on the back or you can solder some wires directly on the ESP32 board.

**Comment by DejanBukovec** [comment]
Hi,
Im flash it with Tasmota and then to ESPHOME and it work. Then Im try figure out which pins are used for voltage and current meter and Im use wrong pins in code and plug do not work anymore. It power up turn on relay and then it shutdown... It can't be reflashed by esphome and it do not connect to wifi(It shut down probably imediately after voltage/current initialization...

To flash it with programmer I will need to know pinout of board, or where I can connect all programmers pins... Im not sure where to find it...

**Comment by felixlungu** [comment]
dejan,

sorry for not not being clear. i don't have the plug you have but from my experience there are 2 ways to program any esp32/esp8266:
 - the pads can be on the larger board properly marked (GND, +3.3V, RX, TX and GPIO0). hence my question to if you can extract the entire pcb from the plug. this should be the case in my opinion since the next solution is a little more involving
 - if they are not there, the small dougther board (the green one on top of the blue one) contains the ESP32 and the pins to program it. first you need to identify what version of the chip is on board since there are many variations which can screw you esphome intalation. when you have it out you can identify which MCU and module you have and what are the pins where you need to soolder the wires.

if the pins are on the larger board, it is much easy to reprogram it. if you need to solder the wires on the small board you need to get the GND, +3.3V, RX, TX, GPIO0 and the CH_EN pins connected to your programmer. CH_EN needs to be connected to +3.3V using a 10Kohm resistor and the GPIO0 to GND directly before you power the chip to put in programming mode.


antoher point is this: Shelly it using on some of their devices a version of the ESP32 which is single core and none the esphome standard configuration will work since all of them are assuming a dual core ESP32. there is a solution which is based on the programing platform configuration used by Tasmota. that is the reason you managed to get the Tasmota running first on the plug. have a look here for more details how to configure the esphome before trying to compile:
https://github.com/esphome-devices/esphome-devices/blob/main/src/docs/devices/Shelly-Plus-i4/index.md

**Comment by felixlungu** [comment]
also this config might help:
https://github.com/esphome-devices/esphome-devices/blob/main/src/docs/devices/Shelly-Plug-S/index.md

**Comment by felixlungu** [comment]
ignore the last link. it appears you a newer version of the plug with ESP32-U4WDH chip. so it is a single core ESP32.

**Comment by bobkersten** [comment]
I've created a PR for this device: https://github.com/esphome-devices/esphome-devices/pull/370

**Comment by felixlungu** [comment]
is working for you? from my usffering with this type of ESP32 (single) i did not manage to get it working until i used in the confing for "esphome:" and "esp32:" something like this:

```
esphome:
  name: ${devic_ename}
  friendly_name: ${friendly_name}
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"
```
or for arduino framework:

```
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  platformio_options:
      board_build.f_cpu: 160000000L
      platform: https://github.com/tasmota/platform-espressif32/releases/download/2023.02.00/platform-espressif32.zip
      framework: arduino
      platform_packages:
        - framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#master
      build_flags:
        - "-DCONFIG_FREERTOS_UNICORE=1"
        - "-DFRAMEWORK_ARDUINO_SOLO1"
      board: esp32-solo1

esp32:
  board: esp32doit-devkit-v1
```

otherwise, i got an esphome build for a dual core ESP32 which enters in a reboot loop.

**Comment by bobkersten** [comment]
The config is working stable for me, on this specific device. I've got it running for over a week now on multiple devices without issues. I use it to switch my office gear (low power < 150w) as well as a bathroom heater (high power > 1500w) from HomeAssistant.

**Comment by DejanBukovec** [comment]
Hi,
Im remove complete PCB from plug case and didn't see any programming pins. I will remove it again and make some pictures... 

Plug use ESP32-U4WDH which can be single or dual core. By checking PN I see that is dual core...
Board use BL0937 chip to measure power, voltage and current.
When Im visualy look on ESP32 chip it looks like U0TXD and U0RXD from chip is not exposed to any pins on green board, except if they are routed under chip...

In homeassistant forum me and few other users(mebrotus, bobkersten) make configuration which work(I didn't test it because my plug die before others found solution for LED's and power). Some user report that after adding led code plug reboot time to time.
https://community.home-assistant.io/t/shelly-plus-plug-s-esphome/544316

Configuration:
```
substitutions:
  device_name: "Shelly Plus Plug S"
  channel_1: Relay
  max_power: "2500" # 2000
  max_temp: "65.0" # 70.0
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1830"
  
esphome:
  name: shelly-plus-plug-s
  friendly_name: shelly-plus-plug-s

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Shelly-Plus-Plug-S"
    password: "testTest123"

time:
  - platform: homeassistant

output:
  - platform: gpio
    id: "relay_output"
    pin: GPIO4

switch:
  - platform: output
    id: "relay"
    name: "${device_name} Relay"
    output: "relay_output"

binary_sensor:
  - platform: gpio
    name: "${device_name} Button"
    pin:
      number: GPIO9
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 5ms

sensor:
  # Internal NTC Temperature sensor
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${device_name} Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "80.0"
        then:
          - switch.turn_off: "relay"  
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO33
    attenuation: 11db
    update_interval: 10s
	
  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO19
      inverted: true
    cf_pin: GPIO10
    cf1_pin: GPIO22
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    change_mode_every: 1
    update_interval: 5s
    current:
      id: current
      unit_of_measurement: A
      accuracy_decimals: 3
      internal: true
    voltage:
      id: voltage
      unit_of_measurement: V
      accuracy_decimals: 1
      internal: true
    power:
      name: "${channel_1} power"
      unit_of_measurement: W
      id: power
      icon: mdi:flash-outline
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: relay
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${device_name}
                data_template:
                  message: Switch turned off because power exceeded ${max_power} W

light:
  - platform: neopixelbus
    variant: 800KBPS
    method:
      type: esp32_rmt
      channel: 0
      pin: GPIO25
      num_leds: 2
      id: rgb_light1
  
  - platform: neopixelbus
    variant: 800KBPS
    method:
      type: esp32_rmt
      channel: 1
      pin: GPIO26
      num_leds: 2
```
